# Generated by Django 4.0.2 on 2022-02-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='evaluationreportt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usert',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workert',
            options={},
        ),
        migrations.AlterModelTable(
            name='assignmentt',
            table=None,
        ),
        migrations.AlterModelTable(
            name='evaluationreportt',
            table=None,
        ),
        migrations.AlterModelTable(
            name='projectt',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usert',
            table=None,
        ),
        migrations.AlterModelTable(
            name='workert',
            table=None,
        ),
    ]
