# Generated by Django 4.0.2 on 2022-02-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0002_alter_assignmentt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentt',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='evaluationreportt',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='projectt',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usert',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='workert',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='assignmentt',
            table='assignment_t',
        ),
        migrations.AlterModelTable(
            name='evaluationreportt',
            table='evaluation_report_t',
        ),
        migrations.AlterModelTable(
            name='projectt',
            table='project_t',
        ),
        migrations.AlterModelTable(
            name='usert',
            table='user_t',
        ),
        migrations.AlterModelTable(
            name='workert',
            table='worker_t',
        ),
    ]
