# Generated by Django 4.0.2 on 2022-04-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0003_alter_assignmentt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workert',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
